#
# Defines Docker aliases.
#
# Author:
#   François Vantomme <akarzim@gmail.com>
#

#
# Aliases
#

# Docker
alias dk='docker'
alias dka='docker attach'
alias dkb='docker build'
alias dkd='docker diff'
alias dkdf='docker system df'
alias dke='docker exec'
alias dkE='docker exec -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t'
alias dkh='docker history'
alias dki='docker images'
alias dkin='docker inspect'
alias dkim='docker import'
alias dkk='docker kill'
alias dkkh='docker kill -s HUP'
alias dkl='docker logs'
alias dkL='docker logs -f'
alias dkli='docker login'
alias dklo='docker logout'
alias dkls='docker ps'
alias dkp='docker pause'
alias dkP='docker unpause'
alias dkpl='docker pull'
alias dkph='docker push'
alias dkps='docker ps'
alias dkpsa='docker ps -a'
alias dkr='docker run'
alias dkR='docker run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm'
alias dkRe='docker run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm --entrypoint /bin/bash'
alias dkRM='docker system prune'
alias dkrm='docker rm'
alias dkrmi='docker rmi'
alias dkrn='docker rename'
alias dks='docker start'
alias dkS='docker restart'
alias dkss='docker stats'
alias dksv='docker save'
alias dkt='docker tag'
alias dktop='docker top'
alias dkup='docker update'
alias dkV='docker volume'
alias dkv='docker version'
alias dkw='docker wait'
alias dkx='docker stop'

## Container (C)
alias dkc='docker container'
alias dkca='docker container attach'
alias dkccp='docker container cp'
alias dkcd='docker container diff'
alias dkce='docker container exec'
alias dkcE='docker container exec -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t'
alias dkcin='docker container inspect'
alias dkck='docker container kill'
alias dkcl='docker container logs'
alias dkcL='docker container logs -f'
alias dkcls='docker container ls'
alias dkcp='docker container pause'
alias dkcpr='docker container prune'
alias dkcrn='docker container rename'
alias dkcS='docker container restart'
alias dkcrm='docker container rm'
alias dkcr='docker container run'
alias dkcR='docker container run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm'
alias dkcRe='docker container run -e COLUMNS=`tput cols` -e LINES=`tput lines` -i -t --rm --entrypoint /bin/bash'
alias dkcs='docker container start'
alias dkcss='docker container stats'
alias dkcx='docker container stop'
alias dkctop='docker container top'
alias dkcP='docker container unpause'
alias dkcup='docker container update'
alias dkcw='docker container wait'

## Image (I)
alias dkI='docker image'
alias dkIb='docker image build'
alias dkIh='docker image history'
alias dkIim='docker image import'
alias dkIin='docker image inspect'
alias dkIls='docker image ls'
alias dkIpr='docker image prune'
alias dkIpl='docker image pull'
alias dkIph='docker image push'
alias dkIrm='docker image rm'
alias dkIsv='docker image save'
alias dkIt='docker image tag'
alias dkIf='function dkIf_(){ docker images -f "reference=*/*/$1*" -f "reference=*$1*" }; dkIf_'

## Volume (V)
alias dkV='docker volume'
alias dkVin='docker volume inspect'
alias dkVls='docker volume ls'
alias dkVpr='docker volume prune'
alias dkVrm='docker volume rm'

## Network (N)
alias dkN='docker network'
alias dkNs='docker network connect'
alias dkNx='docker network disconnect'
alias dkNin='docker network inspect'
alias dkNls='docker network ls'
alias dkNpr='docker network prune'
alias dkNrm='docker network rm'

## System (Y)
alias dkY='docker system'
alias dkYdf='docker system df'
alias dkYpr='docker system prune'

## Stack (K)
alias dkK='docker stack'
alias dkKls='docker stack ls'
alias dkKps='docker stack ps'
alias dkKrm='docker stack rm'

## Swarm (W)
alias dkW='docker swarm'

## CleanUp (rm)
# Clean up exited containers (docker < 1.13)
alias dkrmC='docker rm $(docker ps -qaf status=exited)'

# Clean up dangling images (docker < 1.13)
alias dkrmI='docker rmi $(docker images -qf dangling=true)'

# Pull all tagged images
alias dkplI='docker images --format "{{ .Repository }}" | grep -v "^<none>$" | xargs -L1 docker pull'

# Clean up dangling volumes (docker < 1.13)
alias dkrmV='docker volume rm $(docker volume ls -qf dangling=true)'

# Docker Machine (m)
alias dkm='docker-machine'
alias dkma='docker-machine active'
alias dkmcp='docker-machine scp'
alias dkmin='docker-machine inspect'
alias dkmip='docker-machine ip'
alias dkmk='docker-machine kill'
alias dkmls='docker-machine ls'
alias dkmpr='docker-machine provision'
alias dkmps='docker-machine ps'
alias dkmrg='docker-machine regenerate-certs'
alias dkmrm='docker-machine rm'
alias dkms='docker-machine start'
alias dkmsh='docker-machine ssh'
alias dkmst='docker-machine status'
alias dkmS='docker-machine restart'
alias dkmu='docker-machine url'
alias dkmup='docker-machine upgrade'
alias dkmv='docker-machine version'
alias dkmx='docker-machine stop'

# Docker Compose (c)
if [[ $(uname -s) == "Linux" ]]; then
  alias dkC='docker-compose'
  alias dkCb='docker-compose build'
  alias dkCB='docker-compose build --no-cache'
  alias dkCcf='docker-compose config'
  alias dkCcr='docker-compose create'
  alias dkCd='docker-compose down'
  alias dkCe='docker-compose exec -e COLUMNS=`tput cols` -e LINES=`tput lines`'
  alias dkCev='docker-compose events'
  alias dkCi='docker-compose images'
  alias dkCk='docker-compose kill'
  alias dkCl='docker-compose logs'
  alias dkCL='docker-compose logs -f'
  alias dkCls='docker-compose ps'
  alias dkCp='docker-compose pause'
  alias dkCP='docker-compose unpause'
  alias dkCpl='docker-compose pull'
  alias dkCph='docker-compose push'
  alias dkCpo='docker-compose port'
  alias dkCps='docker-compose ps'
  alias dkCr='docker-compose run -e COLUMNS=`tput cols` -e LINES=`tput lines`'
  alias dkCR='docker-compose run -e COLUMNS=`tput cols` -e LINES=`tput lines` --rm'
  alias dkCrm='docker-compose rm'
  alias dkCs='docker-compose start'
  alias dkCsc='docker-compose scale'
  alias dkCS='docker-compose restart'
  alias dkCt='docker-compose top'
  alias dkCu='docker-compose up'
  alias dkCU='docker-compose up -d'
  alias dkCv='docker-compose version'
  alias dkCx='docker-compose stop'
else
  alias dkC='docker compose'
  alias dkCb='docker compose build'
  alias dkCB='docker compose build --no-cache'
  alias dkCcp='docker compose copy'
  alias dkCcr='docker compose create'
  alias dkCcv='docker compose convert'
  alias dkCd='docker compose down'
  alias dkCe='docker compose exec -e COLUMNS=`tput cols` -e LINES=`tput lines`'
  alias dkCev='docker compose events'
  alias dkCi='docker compose images'
  alias dkCk='docker compose kill'
  alias dkCl='docker compose logs'
  alias dkCL='docker compose logs -f'
  alias dkCls='docker compose ls'
  alias dkCp='docker compose pause'
  alias dkCP='docker compose unpause'
  alias dkCpl='docker compose pull'
  alias dkCph='docker compose push'
  alias dkCpo='docker compose port'
  alias dkCps='docker compose ps'
  alias dkCr='docker compose run -e COLUMNS=`tput cols` -e LINES=`tput lines`'
  alias dkCR='docker compose run -e COLUMNS=`tput cols` -e LINES=`tput lines` --rm'
  alias dkCrm='docker compose rm'
  alias dkCs='docker compose start'
  alias dkCsc='docker-compose scale'
  alias dkCS='docker compose restart'
  alias dkCt='docker compose top'
  alias dkCu='docker compose up'
  alias dkCU='docker compose up -d'
  alias dkCv='docker-compose version'
  alias dkCx='docker compose stop'
fi

# Mutagen
alias mg='mutagen'
alias mgc='mutagen compose'
alias mgcb='mutagen compose build'
alias mgcB='mutagen compose build --no-cache'
alias mgcd='mutagen compose down'
alias mgce='mutagen compose exec -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias mgck='mutagen compose kill'
alias mgcl='mutagen compose logs'
alias mgcL='mutagen compose logs -f'
alias mgcls='mutagen compose ps'
alias mgcp='mutagen compose pause'
alias mgcP='mutagen compose unpause'
alias mgcpl='mutagen compose pull'
alias mgcph='mutagen compose push'
alias mgcps='mutagen compose ps'
alias mgcr='mutagen compose run -e COLUMNS=`tput cols` -e LINES=`tput lines`'
alias mgcR='mutagen compose run -e COLUMNS=`tput cols` -e LINES=`tput lines` --rm'
alias mgcrm='mutagen compose rm'
alias mgcs='mutagen compose start'
alias mgcsc='mutagen compose scale'
alias mgcS='mutagen compose restart'
alias mgcu='mutagen compose up'
alias mgcU='mutagen compose up -d'
alias mgcv='mutagen compose version'
alias mgcx='mutagen compose stop'
